// Generated by CoffeeScript 1.5.0
(function() {
  var cluster, colors, options, path;

  cluster = require("cluster");

  path = require("path");

  colors = require("colors");

  options = {
    hook: false,
    includeModules: false,
    main: require.main.filename,
    ignore: /(\/\.|~$)/
  };

  module.exports = function(ops) {
    var chokidar, initial, key, lastErr, value, watcher, worker;
    if (typeof ops === "string" || ops instanceof String) {
      options.main = path.resolve(ops);
    } else {
      for (key in ops) {
        value = ops[key];
        options[key] = value;
      }
    }
    if (cluster.isMaster) {
      cluster.setupMaster({
        exec: path.join(path.dirname(module.filename), "launcher.js")
      });
      chokidar = require("chokidar");
      initial = options.hook ? options.main : path.dirname(options.main);
      watcher = chokidar.watch(initial, {
        ignored: options.ignore,
        ignoreInitial: true
      });
      lastErr = "";
      worker = cluster.fork();
      cluster.on("exit", function(dead, code, signal) {
        if (worker.err && worker.err !== lastErr) {
          console.log("[piping]".bold.red, "can't execute file:", options.main);
          console.log("[piping]".bold.red, "error given was:", worker.err);
          console.log("[piping]".bold.red, "further repeats of this error will be suppressed...");
        }
        lastErr = worker.err;
        return worker = cluster.fork();
      });
      cluster.on("online", function(worker) {
        worker.send(options);
        return worker.on("message", function(message) {
          if (!message.err) {
            return watcher.add(message.file);
          } else {
            return worker.err = message.err;
          }
        });
      });
      watcher.on("change", function(file) {
        console.log("[piping]".bold.red, "File", path.relative(process.cwd(), file), "has changed, reloading.");
        return worker.destroy();
      });
      return false;
    } else {
      return true;
    }
  };

}).call(this);
